### ISSUE TITLE
Don't repeat mistake of "Pidora": you made another cross-language swearing title

### ISSUE THREAD

**Issue by Wohlstand** [raa-eruanna/RaspZDoom#1]
I think, you know the "Pidora" - a Fedora linux distro for Raspberry Pi released by Canadian folks. Unfortunately, their title is matching to rude Russian swearing word `пидор` [peedor] which applying to offend a gay man. You may see a note at [their official site](http://pidora.ca/).

However, the "PiZDoom" is a cognate word to the `пизда` [peezda] word which literally means a "vagina" (in English the "cunt"). I don't think it's a good idea...

**Comment by madame-rachelle** [comment]
I will see about changing it to something more acceptable. It is not my intention to go out of my way to offend folks.

**Comment by madame-rachelle** [comment]
Renamed.

**Comment by Wohlstand** [comment]
I see, now it's fine :3
Thanks for understanding :fox_face: :smiley:
