### ISSUE TITLE
Libretro port?

### ISSUE THREAD

**Issue by VGkav** [raa-eruanna/RaspZDoom#2]
Can you create a libretro port of ZDoom? That'd be great!

**Comment by DartPower** [comment]
I think this question needs to original GZDoom (LZDoom), this repo not maintained 😭 
Will be best, when LZDoom or GZDoom will be as libretro... RetroArch is best!

**Comment by madame-rachelle** [comment]
Sorry it's not my intent to abandon this at all. I do not have RetroArch and I do not have a whole lot of SD cards.

Between helping with GZDoom itself and a bunch of RL projects I don't have much time to look after this. I'll try and do an update soon though.

**Comment by VGkav** [comment]
> 
> 
> Sorry it's not my intent to abandon this at all. I do not have RetroArch and I do not have a whole lot of SD cards.
> 
> Between helping with GZDoom itself and a bunch of RL projects I don't have much time to look after this. I'll try and do an update soon though.

No problem but I recommend you check out Retroarch and its libretro , it is a cool platform

https://docs.libretro.com/development/libretro-overview/
